In [9]:
# Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Formatação global para reduzir casas decimais

pd.set_option('display.float_format', '{:.2f}',format )

sns.set(style="whitegrid")

ValueError: Must provide an even number of non-keyword arguments

In [2]:
# Carregamento do Dataset
disney_movies = pd.read_csv("disney_movies.csv")
disney_movies.head()

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730

In [3]:
# Descrição dos dados
disney_movies.dtypes

movie_title                   str
release_date                  str
genre                         str
mpaa_rating                   str
total_gross                 int64
inflation_adjusted_gross    int64
dtype: object

In [4]:
# Valores nulos
disney_movies.isna().sum()

movie_title                  0
release_date                 0
genre                       17
mpaa_rating                 56
total_gross                  0
inflation_adjusted_gross     0
dtype: int64

In [6]:
# Valores distintos
disney_movies.nunique()

movie_title                 573
release_date                553
genre                        12
mpaa_rating                   5
total_gross                 576
inflation_adjusted_gross    576
dtype: int64

In [7]:
# Estatísticas numéricas
disney_movies.describe()

        total_gross  inflation_adjusted_gross
count  5.790000e+02              5.790000e+02
mean   6.470179e+07              1.187625e+08
std    9.301301e+07              2.860853e+08
min    0.000000e+00              0.000000e+00
25%    1.278886e+07              2.274123e+07
50%    3.070245e+07              5.515978e+07
75%    7.570903e+07              1.192020e+08
max    9.366622e+08              5.228953e+09

In [17]:
# Tratamento de Dados
# Converter datas

df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")

In [19]:
# Remover filmes sem bilheteria
df = df[df["total_gross"]>0]

In [20]:
df

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923
577,Moana,2016-11-23,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936

In [21]:
# Preencher valores nulos
df["genre"] = df["genre"]. fillna("Unknown")
df["mpaa_rating"] = df["mpaa_rating"].fillna("Unrated")

In [24]:
# Criar coluna de década

df["decade"] = (df["release_date"].dt.year // 10) *10

In [25]:
df

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross,decade
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251,1930
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052,1940
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808,1940
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579,1940
4,Cinderella,1950-02-15,Drama,G,85000000,920608730,1950
...,...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979,2010
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389,2010
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923,2010
577,Moana,2016-11-23,Adventure,PG,246082029,246082029,2010
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936,2010