In [6]:
# Importação das bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


sns.set(style="whitegrid")

In [24]:
# Carregamento do Dataset
disney_movies = pd.read_csv("disney_movies.csv")
disney_movies.head()

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730

In [8]:
# Descrição dos dados
disney_movies.dtypes

movie_title                   str
release_date                  str
genre                         str
mpaa_rating                   str
total_gross                 int64
inflation_adjusted_gross    int64
dtype: object

In [9]:
# Valores nulos
disney_movies.isna().sum()

movie_title                  0
release_date                 0
genre                       17
mpaa_rating                 56
total_gross                  0
inflation_adjusted_gross     0
dtype: int64

In [10]:
# Valores distintos
disney_movies.nunique()

movie_title                 573
release_date                553
genre                        12
mpaa_rating                   5
total_gross                 576
inflation_adjusted_gross    576
dtype: int64

In [23]:
# Estatísticas numéricas
disney_movies.describe()

,release_date,total_gross,inflation_adjusted_gross,decade
count,575,5.750000e+02,5.750000e+02,575.000000
mean,1998-08-12 15:24:06.260869,6.515189e+07,1.195887e+08,1993.652174
min,1937-12-21 00:00:00,2.815000e+03,2.984000e+03,1930.000000
25%,1993-04-19 12:00:00,1.305192e+07,2.360310e+07,1990.000000
50%,1998-09-11 00:00:00,3.083391e+07,5.541762e+07,1990.000000
75%,2006-02-27 12:00:00,7.602557e+07,1.195395e+08,2000.000000
max,2016-12-16 00:00:00,9.366622e+08,5.228953e+09,2010.000000
std,NaN,9.317903e+07,2.869079e+08,11.561865

In [12]:
# Tratamento de Dados
# Converter datas

disney_movies["release_date"] = pd.to_datetime(disney_movies["release_date"], errors="coerce")

In [13]:
# Remover filmes sem bilheteria
disney_movies = disney_movies[disney_movies["total_gross"]>0]

In [14]:
disney_movies

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579
4,Cinderella,1950-02-15,Drama,G,85000000,920608730
...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923
577,Moana,2016-11-23,Adventure,PG,246082029,246082029
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936

In [ ]:
# Preencher valores nulos em gênero e rating
disney_movies["genre"] = disney_movies["genre"]. fillna("Unknown")
disney_movies["mpaa_rating"] = disney_movies["mpaa_rating"].fillna("Unrated")

In [16]:
# Criar coluna de década

disney_movies["decade"] = (disney_movies["release_date"].dt.year // 10) *10

In [17]:
disney_movies

,movie_title,release_date,genre,mpaa_rating,total_gross,inflation_adjusted_gross,decade
0,Snow White and the Seven Dwarfs,1937-12-21,Musical,G,184925485,5228953251,1930
1,Pinocchio,1940-02-09,Adventure,G,84300000,2188229052,1940
2,Fantasia,1940-11-13,Musical,G,83320000,2187090808,1940
3,Song of the South,1946-11-12,Adventure,G,65000000,1078510579,1940
4,Cinderella,1950-02-15,Drama,G,85000000,920608730,1950
...,...,...,...,...,...,...,...
574,The Light Between Oceans,2016-09-02,Drama,PG-13,12545979,12545979,2010
575,Queen of Katwe,2016-09-23,Drama,PG,8874389,8874389,2010
576,Doctor Strange,2016-11-04,Adventure,PG-13,232532923,232532923,2010
577,Moana,2016-11-23,Adventure,PG,246082029,246082029,2010
578,Rogue One: A Star Wars Story,2016-12-16,Adventure,PG-13,529483936,529483936,2010

In [ ]:
Perguntas